function add(x,y){
    return x+y;
}

function subtract(x,y){
    return x-y;
}

function divide(x,y){
    if (y === 0){
        return "Cannot divide by zero.";
    }
    else {
        return x/y
    }
}

function multiply(x,y){
    return x*y;
}

function operate(x,y,op){
    switch(op){
        case "+":
            return add(x,y);
        case "-":
            return subtract(x,y);
        case "/":
            return divide(x,y);
        case "*":
            return multiply(x,y); 
    }
}

function clickNumber() {
    console.log("number was clicked");
    console.log(this);
    console.log(this.textContent);
    updateDisplay(this.textContent);
}

function clickSymbol(){
    console.log("symbol was clicked");
    
}

function updateDisplay(textToShow) {
    // removes whitespace generated by textContent
    display.textContent += textToShow.replace(/[\n\r]+|[\s]{2,}/g, ' ').trim()
}

const display = document.querySelector("#display");
const numberButtons = document.querySelectorAll(".button.number");
const symbolButtons = document.querySelectorAll(".button.symbol");

symbolButtons.forEach(button => button.addEventListener('click', clickSymbol));
numberButtons.forEach(button => button.addEventListener('click', clickNumber));